# Generated by Django 3.0.8 on 2021-03-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='confirmpass',
            field=models.CharField(default='', max_length=30),
        ),
    ]
